-- AlterTable
ALTER TABLE "HeroSection" ALTER COLUMN "mainText" DROP DEFAULT,
ALTER COLUMN "subtext" DROP DEFAULT,
ALTER COLUMN "ctaButtonText" DROP DEFAULT,
ALTER COLUMN "ctaButtonUrl" DROP DEFAULT;
